language: php
dist: bionic

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer require php-coveralls/php-coveralls:2.2.0

install:
    - travis_retry composer -n install --prefer-dist

script:
    - ./vendor/bin/phpunit --configuration phpunit.build.xml --coverage-clover ./tests/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v

jobs:
    include:
        - stage: Test
          php: 7.4

    allow_failures:
        - env: DEPENDENCIES=dev
